language: node_js
node_js:
- '15'
script:
- npm run build
deploy:
  provider: npm
  email: visikov@gmail.com
  api_key:
    secure: GyRktw+zdaGX8I8DB282PTPg6fqCNcGP2PA9eCMTpPpf7Gkv22UiTCbO/bHV+GY+kIHm0EXw9QDD//PxZTuSv9K8WmzSl7E97I3411sIQ4abTTPTQMiCDTrswrZuJS1eHOtJEI6tyB+H2vRft9OtjXFa69IMRRhRZotlin7NekmZeL+JmC9JwhXXh8W+oiQI5Bcmqt7xrqeC6OmAsYLp1C615Cvhhv+ZWSjOt6J5IDSpSsVMmSIvovBB1RQPgQOCfS0OmRqN29l22bvpU0CnVHSL9ytYluCUvMefbgHSd/FgINSxpI/iaZPzdCjEAh2LdUEzcfgx3GR+eJt96trd3AisuM7Gh3xRAMcVou4LE4SeGvn+nIW5dqLDrRW8x3d0E/bF5Mz+5fxAWrIzMgugcJn8DpYZiAb10GGWXTviD+nB8v/Aw0Z+5le+SdSccbtc4Qg/+fKSAfwvAnYQ6Kz20Oa25We3kIajF2KCfBcXc3FM3OPFCofSwNG6TSUCMNsEr8G2/OJY9tFbZ+b5yXY1YOfgKVaoPQAuIYmVHBTyQwLbuBY8rm93h3MaugghB3SteyDDUGyHCcswLHYqJzKjQqA+LTocIdm2mk4lsyJk4DlAMXfa75Yic7KsvHt5s9LAHhWNRPssW8IOpLVWL3TEKICp07pkGrO1ag8qUvGUlh8=
  on:
    tags: true
    repo: notVitaliy/spacetraders-io
  skip_cleanup: 'true'
